### ISSUE TITLE
CR001_enhancement

### ISSUE THREAD

**Issue by sachinnaik1** [snimalan/NUS_IIS_SE22PT7_SCM#1]
@snimalan
Study NUS_IIS_SE22PT7_SCM/vmcs/doc/CR/ChangeRequestForm_CR001_enhancement.doc
and proceed to the changes.

**Comment by snimalan** [comment]
1. @banukobhan - Please analysis this enhancement
2. @Carthigan - Please implement the changes

**Comment by banukobhan** [comment]
@Carthigan
Please start implementation.

**Comment by Carthigan** [comment]
@eaindranilar
The changes have been implemented.
Please test the enhancement.
Thanks

**Comment by eaindranilar** [comment]
@sachinnaik1 
I tested and verified.

**Comment by Carthigan** [comment]
@eaindranilar
The changes have been implemented.
Please test the enhancement.
Thanks

**Comment by eaindranilar** [comment]
@sachinnaik1 
It is tested and verified.

**Comment by sachinnaik1** [comment]
@bobothaung
Please verify.

**Comment by ghost** [comment]
@sachinnaik1 
It is tested and verified.

**Comment by sachinnaik1** [comment]
@bobothaung
Please verify.

**Comment by bobothaung** [comment]
@sachinnaik1 
I have done the testing, It is verified OK

**Comment by sachinnaik1** [comment]
@nicolaurent 
Please merge this changes and make a Release.

**Comment by nicolaurent** [comment]
@sachinnaik1 
I have made the release. Please refer to the link below
https://github.com/snimalan/NUS_IIS_SE22PT7_SCM/releases/tag/R1.0.9

**Comment by sachinnaik1** [comment]
Thank you Team.
