### ISSUE TITLE
CR002_defect

### ISSUE THREAD

**Issue by sachinnaik1** [snimalan/NUS_IIS_SE22PT7_SCM#2]
@snimalan
Study NUS_IIS_SE22PT7_SCM/vmcs/doc/CR/ChangeRequestForm_CR002_defect.doc
and proceed to the changes.

**Comment by snimalan** [comment]
1. @banukobhan - Please analysis this defect  
2. @pradeep-subramanian - Please implement the changes

**Comment by banukobhan** [comment]
@pradeep-subramanian 
Please start implementation.

**Comment by pradeep-subramanian** [comment]
@eaindranilar

The changes have been implemented.

Please help to test the changes.

Thanks.

**Comment by eaindranilar** [comment]
@sachinnaik1 
I tested and verified.

**Comment by sachinnaik1** [comment]
@bobothaung

Please verify

**Comment by pradeep-subramanian** [comment]
@eaindranilar

The changes have been implemented.

Please help to test the changes.

Thanks.

**Comment by ghost** [comment]
@sachinnaik1 
It is tested and verified.

**Comment by sachinnaik1** [comment]
@bobothaung
Please verify.

**Comment by bobothaung** [comment]
@sachinnaik1 
I have done the testing, It is verified OK

**Comment by sachinnaik1** [comment]
@nicolaurent,
Please merge this changes and make a Release.

**Comment by nicolaurent** [comment]
@sachinnaik1 
I have made the release. Please refer to the link below
https://github.com/snimalan/NUS_IIS_SE22PT7_SCM/releases/tag/R1.0.9

**Comment by sachinnaik1** [comment]
Thank you Team
